# Generated by Django 4.0.1 on 2022-01-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('noteColor', models.CharField(choices=[('red', 'r'), ('green', 'g'), ('blue', 'b')], max_length=10, verbose_name='note color')),
                ('isArchived', models.BooleanField(verbose_name='is archived')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
            },
        ),
    ]
